### ISSUE TITLE
Setup Guide Doen't Work

### ISSUE THREAD

**Issue by AndreasRonaldi** [ifunpar/SharIF-Judge#17]
<details>

```
[Fri Jun 07 08:58:43.968396 2024] [ssl:warn] [pid 11932:tid 372] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 07 08:58:44.004415 2024] [core:warn] [pid 11932:tid 372] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jun 07 08:58:44.008413 2024] [ssl:warn] [pid 11932:tid 372] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 07 08:58:44.043186 2024] [mpm_winnt:notice] [pid 11932:tid 372] AH00455: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4 configured -- resuming normal operations
[Fri Jun 07 08:58:44.043186 2024] [mpm_winnt:notice] [pid 11932:tid 372] AH00456: Apache Lounge VS16 Server built: Mar  7 2023 13:21:03
[Fri Jun 07 08:58:44.043186 2024] [core:notice] [pid 11932:tid 372] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 07 08:58:44.047367 2024] [mpm_winnt:notice] [pid 11932:tid 372] AH00418: Parent: Created child process 14856
[Fri Jun 07 08:58:44.302031 2024] [ssl:warn] [pid 14856:tid 372] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 07 08:58:44.336620 2024] [ssl:warn] [pid 14856:tid 372] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 07 08:58:44.361580 2024] [mpm_winnt:notice] [pid 14856:tid 372] AH00354: Child: Starting 150 worker threads.
[Fri Jun 07 08:58:53.686400 2024] [php:error] [pid 14856:tid 1900] [client ::1:20716] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown database 'judge' in C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php:110\nStack trace:\n#0 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php(110): mysqli->real_connect('p:localhost', 'root', Object(SensitiveParameterValue), 'judge', NULL, NULL, 0)\n#1 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php(123): CI_DB_mysqli_driver->db_connect(true)\n#2 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_driver.php(390): CI_DB_mysqli_driver->db_pconnect()\n#3 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB.php(206): CI_DB_driver->initialize()\n#4 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(331): DB(Array, NULL)\n#5 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\drivers\\Session_cookie.php(250): CI_Loader->database()\n#6 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(665): CI_Session_cookie->initialize()\n#7 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Driver.php(176): CI_Session_driver->decorate(Object(CI_Session))\n#8 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(166): CI_Driver_Library->load_driver('cookie')\n#9 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(141): CI_Session->load_driver('cookie')\n#10 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1172): CI_Session->__construct()\n#11 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1044): CI_Loader->_ci_init_class('Session', '', NULL, 'session')\n#12 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(200): CI_Loader->_ci_load_class('Session', NULL, NULL)\n#13 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(691): CI_Loader->library('Session/session', NULL, NULL)\n#14 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1234): CI_Loader->driver('Session/session')\n#15 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(146): CI_Loader->_ci_autoloader()\n#16 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Controller.php(68): CI_Loader->initialize()\n#17 C:\\xampp\\htdocs\\SharIF-Judge\\application\\controllers\\Dashboard.php(15): CI_Controller->__construct()\n#18 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\CodeIgniter.php(342): Dashboard->__construct()\n#19 C:\\xampp\\htdocs\\SharIF-Judge\\index.php(302): require_once('C:\\\\xampp\\\\htdocs...')\n#20 {main}\n  thrown in C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php on line 110
[Fri Jun 07 08:59:31.076339 2024] [php:error] [pid 14856:tid 1896] [client ::1:20721] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'judge.shj_sessions' doesn't exist in C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php:212\nStack trace:\n#0 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php(212): mysqli->query('INSERT INTO `sh...')\n#1 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_driver.php(740): CI_DB_mysqli_driver->_execute('INSERT INTO `sh...')\n#2 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_driver.php(605): CI_DB_driver->simple_query('INSERT INTO `sh...')\n#3 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_query_builder.php(1589): CI_DB_driver->query('INSERT INTO `sh...')\n#4 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\drivers\\Session_cookie.php(525): CI_DB_query_builder->insert('sessions', Array)\n#5 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\drivers\\Session_cookie.php(274): CI_Session_cookie->_sess_create()\n#6 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(665): CI_Session_cookie->initialize()\n#7 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Driver.php(176): CI_Session_driver->decorate(Object(CI_Session))\n#8 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(166): CI_Driver_Library->load_driver('cookie')\n#9 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(141): CI_Session->load_driver('cookie')\n#10 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1172): CI_Session->__construct()\n#11 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1044): CI_Loader->_ci_init_class('Session', '', NULL, 'session')\n#12 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(200): CI_Loader->_ci_load_class('Session', NULL, NULL)\n#13 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(691): CI_Loader->library('Session/session', NULL, NULL)\n#14 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1234): CI_Loader->driver('Session/session')\n#15 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(146): CI_Loader->_ci_autoloader()\n#16 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Controller.php(68): CI_Loader->initialize()\n#17 C:\\xampp\\htdocs\\SharIF-Judge\\application\\controllers\\Dashboard.php(15): CI_Controller->__construct()\n#18 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\CodeIgniter.php(342): Dashboard->__construct()\n#19 C:\\xampp\\htdocs\\SharIF-Judge\\index.php(302): require_once('C:\\\\xampp\\\\htdocs...')\n#20 {main}\n  thrown in C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php on line 212
[Fri Jun 07 09:01:16.249712 2024] [php:error] [pid 14856:tid 1892] [client ::1:5458] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'judge.shj_sessions' doesn't exist in C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php:212\nStack trace:\n#0 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php(212): mysqli->query('INSERT INTO `sh...')\n#1 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_driver.php(740): CI_DB_mysqli_driver->_execute('INSERT INTO `sh...')\n#2 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_driver.php(605): CI_DB_driver->simple_query('INSERT INTO `sh...')\n#3 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_query_builder.php(1589): CI_DB_driver->query('INSERT INTO `sh...')\n#4 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\drivers\\Session_cookie.php(525): CI_DB_query_builder->insert('sessions', Array)\n#5 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\drivers\\Session_cookie.php(274): CI_Session_cookie->_sess_create()\n#6 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(665): CI_Session_cookie->initialize()\n#7 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Driver.php(176): CI_Session_driver->decorate(Object(CI_Session))\n#8 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(166): CI_Driver_Library->load_driver('cookie')\n#9 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(141): CI_Session->load_driver('cookie')\n#10 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1172): CI_Session->__construct()\n#11 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1044): CI_Loader->_ci_init_class('Session', '', NULL, 'session')\n#12 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(200): CI_Loader->_ci_load_class('Session', NULL, NULL)\n#13 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(691): CI_Loader->library('Session/session', NULL, NULL)\n#14 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1234): CI_Loader->driver('Session/session')\n#15 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(146): CI_Loader->_ci_autoloader()\n#16 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Controller.php(68): CI_Loader->initialize()\n#17 C:\\xampp\\htdocs\\SharIF-Judge\\application\\controllers\\Dashboard.php(15): CI_Controller->__construct()\n#18 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\CodeIgniter.php(342): Dashboard->__construct()\n#19 C:\\xampp\\htdocs\\SharIF-Judge\\index.php(302): require_once('C:\\\\xampp\\\\htdocs...')\n#20 {main}\n  thrown in C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php on line 212
[Fri Jun 07 09:01:17.835988 2024] [php:error] [pid 14856:tid 1892] [client ::1:5460] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'judge.shj_sessions' doesn't exist in C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php:212\nStack trace:\n#0 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php(212): mysqli->query('INSERT INTO `sh...')\n#1 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_driver.php(740): CI_DB_mysqli_driver->_execute('INSERT INTO `sh...')\n#2 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_driver.php(605): CI_DB_driver->simple_query('INSERT INTO `sh...')\n#3 C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\DB_query_builder.php(1589): CI_DB_driver->query('INSERT INTO `sh...')\n#4 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\drivers\\Session_cookie.php(525): CI_DB_query_builder->insert('sessions', Array)\n#5 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\drivers\\Session_cookie.php(274): CI_Session_cookie->_sess_create()\n#6 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(665): CI_Session_cookie->initialize()\n#7 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Driver.php(176): CI_Session_driver->decorate(Object(CI_Session))\n#8 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(166): CI_Driver_Library->load_driver('cookie')\n#9 C:\\xampp\\htdocs\\SharIF-Judge\\system\\libraries\\Session\\Session.php(141): CI_Session->load_driver('cookie')\n#10 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1172): CI_Session->__construct()\n#11 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1044): CI_Loader->_ci_init_class('Session', '', NULL, 'session')\n#12 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(200): CI_Loader->_ci_load_class('Session', NULL, NULL)\n#13 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(691): CI_Loader->library('Session/session', NULL, NULL)\n#14 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1234): CI_Loader->driver('Session/session')\n#15 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(146): CI_Loader->_ci_autoloader()\n#16 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Controller.php(68): CI_Loader->initialize()\n#17 C:\\xampp\\htdocs\\SharIF-Judge\\application\\controllers\\Dashboard.php(15): CI_Controller->__construct()\n#18 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\CodeIgniter.php(342): Dashboard->__construct()\n#19 C:\\xampp\\htdocs\\SharIF-Judge\\index.php(302): require_once('C:\\\\xampp\\\\htdocs...')\n#20 {main}\n  thrown in C:\\xampp\\htdocs\\SharIF-Judge\\system\\database\\drivers\\mysqli\\mysqli_driver.php on line 212
[Fri Jun 07 09:06:07.175038 2024] [php:error] [pid 14856:tid 1892] [client ::1:11352] PHP Fatal error:  Uncaught Error: Class "Twig_Environment" not found in C:\\xampp\\htdocs\\SharIF-Judge\\application\\libraries\\Twig.php:69\nStack trace:\n#0 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1171): Twig->__construct(Array)\n#1 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1044): CI_Loader->_ci_init_class('Twig', '', Array, 'twig')\n#2 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(200): CI_Loader->_ci_load_class('Twig', NULL, NULL)\n#3 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1251): CI_Loader->library('twig')\n#4 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(146): CI_Loader->_ci_autoloader()\n#5 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Controller.php(68): CI_Loader->initialize()\n#6 C:\\xampp\\htdocs\\SharIF-Judge\\application\\controllers\\Dashboard.php(15): CI_Controller->__construct()\n#7 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\CodeIgniter.php(342): Dashboard->__construct()\n#8 C:\\xampp\\htdocs\\SharIF-Judge\\index.php(302): require_once('C:\\\\xampp\\\\htdocs...')\n#9 {main}\n  thrown in C:\\xampp\\htdocs\\SharIF-Judge\\application\\libraries\\Twig.php on line 69
[Fri Jun 07 09:06:53.218097 2024] [php:error] [pid 14856:tid 1892] [client ::1:11371] PHP Fatal error:  Uncaught Error: Class "Twig_Environment" not found in C:\\xampp\\htdocs\\SharIF-Judge\\application\\libraries\\Twig.php:69\nStack trace:\n#0 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1171): Twig->__construct(Array)\n#1 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1044): CI_Loader->_ci_init_class('Twig', '', Array, 'twig')\n#2 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(200): CI_Loader->_ci_load_class('Twig', NULL, NULL)\n#3 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1251): CI_Loader->library('twig')\n#4 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(146): CI_Loader->_ci_autoloader()\n#5 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Controller.php(68): CI_Loader->initialize()\n#6 C:\\xampp\\htdocs\\SharIF-Judge\\application\\controllers\\Install.php(14): CI_Controller->__construct()\n#7 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\CodeIgniter.php(342): Install->__construct()\n#8 C:\\xampp\\htdocs\\SharIF-Judge\\index.php(302): require_once('C:\\\\xampp\\\\htdocs...')\n#9 {main}\n  thrown in C:\\xampp\\htdocs\\SharIF-Judge\\application\\libraries\\Twig.php on line 69
[Fri Jun 07 09:08:43.145395 2024] [php:error] [pid 14856:tid 1892] [client ::1:38065] PHP Fatal error:  Uncaught Error: Call to a member function userdata() on null in C:\\xampp\\htdocs\\SharIF-Judge\\application\\models\\User.php:21\nStack trace:\n#0 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(286): User->__construct()\n#1 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(226): CI_Loader->model('User', 'user', false)\n#2 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(1258): CI_Loader->model(Array)\n#3 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Loader.php(146): CI_Loader->_ci_autoloader()\n#4 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\Controller.php(68): CI_Loader->initialize()\n#5 C:\\xampp\\htdocs\\SharIF-Judge\\application\\controllers\\Install.php(14): CI_Controller->__construct()\n#6 C:\\xampp\\htdocs\\SharIF-Judge\\system\\core\\CodeIgniter.php(342): Install->__construct()\n#7 C:\\xampp\\htdocs\\SharIF-Judge\\index.php(302): require_once('C:\\\\xampp\\\\htdocs...')\n#8 {main}\n  thrown in C:\\xampp\\htdocs\\SharIF-Judge\\application\\models\\User.php on line 21
```

</details>

**Comment by pascalalfadian** [comment]
Checking this now...

**Comment by pascalalfadian** [comment]
Update: Potentially due to old version of PHP. Now working in Version-1.1 branch. Next would be to try to upgrade Twig and fix other errors.

@AndreasRonaldi can you help to reply with something in this comment? So I get a reminder to continue working on this. Thanks.

**Comment by AndreasRonaldi** [comment]
Thank you for Addressing & Checking this bug, I hope this issue is resolved. Thank you @pascalalfadian.

**Comment by pascalalfadian** [comment]
Hi @AndreasRonaldi 

Can you try to pull the latest changes? The problem was due to SharIF Judge is using database for session, but there was no table creation instruction. I changed the default to files, but also at the same time update many stuffs to make it compatible with PHP 8.3.

I'm closing this issue now. Contact me privately through e-mail if you have difficulties.

Thanks.
